Adds more error cases in hit the point functionality
NeowayLabs/dojo pull request #10
Opened 2017-03-16 21:23 UTC by OctavioBR

Guys, after a long discussion, we decided to keep developing this app. Here goes some more tests that we managed to code during the last half of our meeting :sweat_smile:

2017-03-16 21:49 UTC, fernandoguedes commented
Nice!

2017-03-20 21:28 UTC, vitorarins requested changes
Looks ok. Just have some doubts about the error handling 😉

2017-03-20 21:28 UTC, vitorarins commented on client/karma.conf.js
> +      ]
Thanks 😅

2017-03-20 21:28 UTC, vitorarins commented on client/src/clock-register/clock-register.controller.js
> +                if (error.data.message) {
I think this handling should be done in the first `if` on line 31. Also it looks like an inconsistency with `error.message`.

2017-03-20 21:28 UTC, vitorarins commented on client/src/clock-register/clock-register.directive.spec.js
> +          $httpBackend.expect('POST', '/api/v1/clock/hit').respond(401, 'Authentication Failed');
I think this should return an object like the following test.

2017-03-20 22:35 UTC, OctavioBR commented on client/src/clock-register/clock-register.controller.js
> +                if (error.data.message) {
Absolutely. We completely forgot about that `if` in the beginning of `catch` callback. As far as I remember, we started discussing about "error 500" and using a "convention" to only deal with more specific body formats (like objects that contains a certain key), then we did this. But I agree with you that we should be more concise.

2017-03-20 22:36 UTC, OctavioBR commented on client/src/clock-register/clock-register.directive.spec.js
> +          $httpBackend.expect('POST', '/api/v1/clock/hit').respond(401, 'Authentication Failed');
Yes! I think we should stick to objects or only direct body strings. Not mixing both!

2017-04-09 02:52 UTC, vitorarins approved these changes

2023-06-29 09:35 UTC, OctavioBR commented
Abandoned 💀

2023-06-29 09:35 UTC, closed without merging